Version=1
# 6209.43212890625
WorldMap.CenterX=6209.43212890625

# 5340.9521484375
WorldMap.CenterY=5340.9521484375

# true
WorldMap.HighlightStreet=true

# true
WorldMap.Isometric=true

# true
WorldMap.LargeStreetLabel=true

# true
WorldMap.PlaceNames=true

# true
WorldMap.Players=true

# false
WorldMap.ShowPrintMedia=false

# true
WorldMap.ShowStreetNames=true

# true
WorldMap.ShowSymbolsUI=true

# true
WorldMap.Symbols=true

# false
WorldMap.TerrainImage=false

# 15.5
WorldMap.Zoom=15.5

# 17.0
MiniMap.Zoom=17.0

# true
MiniMap.Isometric=true

# false
MiniMap.ShowSymbols=false

# true
MiniMap.StartVisible=true

# false
MiniMap.TerrainImage=false