Version=1
# 6139.27734375
WorldMap.CenterX=6139.27734375

# 5421.55908203125
WorldMap.CenterY=5421.55908203125

# true
WorldMap.HighlightStreet=true

# true
WorldMap.Isometric=true

# true
WorldMap.LargeStreetLabel=true

# true
WorldMap.PlaceNames=true

# true
WorldMap.Players=true

# false
WorldMap.ShowPrintMedia=false

# true
WorldMap.ShowStreetNames=true

# true
WorldMap.ShowSymbolsUI=true

# true
WorldMap.Symbols=true

# false
WorldMap.TerrainImage=false

# 15.0
WorldMap.Zoom=15.0

# 17.5
MiniMap.Zoom=17.5

# true
MiniMap.Isometric=true

# false
MiniMap.ShowSymbols=false

# true
MiniMap.StartVisible=true

# false
MiniMap.TerrainImage=false