Version=1
# 12743.2216796875
WorldMap.CenterX=12743.2216796875

# 846.2240600585938
WorldMap.CenterY=846.2240600585938

# true
WorldMap.HighlightStreet=true

# true
WorldMap.Isometric=true

# true
WorldMap.LargeStreetLabel=true

# true
WorldMap.PlaceNames=true

# true
WorldMap.Players=true

# true
WorldMap.ShowPrintMedia=true

# true
WorldMap.ShowStreetNames=true

# true
WorldMap.ShowSymbolsUI=true

# true
WorldMap.Symbols=true

# false
WorldMap.TerrainImage=false

# 13.5
WorldMap.Zoom=13.5

# 15.5
MiniMap.Zoom=15.5

# true
MiniMap.Isometric=true

# false
MiniMap.ShowSymbols=false

# true
MiniMap.StartVisible=true

# false
MiniMap.TerrainImage=false